# Generated by Django 5.2 on 2025-04-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hardware_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blurb', models.CharField(max_length=500)),
                ('description', models.CharField()),
            ],
        ),
    ]
