# Generated by Django 5.2 on 2025-04-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0003_rename_hardware_projects_hardware_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blurb', models.CharField(max_length=500)),
                ('description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='software_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blurb', models.CharField(max_length=500)),
                ('description', models.CharField()),
            ],
        ),
    ]
