# Generated by Django 5.2 on 2025-04-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0004_event_software_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(default=models.CharField(max_length=100), max_length=30),
        ),
        migrations.AddField(
            model_name='hardware_project',
            name='link',
            field=models.CharField(default=models.CharField(max_length=100), max_length=30),
        ),
        migrations.AddField(
            model_name='software_project',
            name='link',
            field=models.CharField(default=models.CharField(max_length=100), max_length=30),
        ),
    ]
