# Generated by Django 5.2 on 2025-04-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0005_event_link_hardware_project_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blurb', models.CharField(max_length=500)),
                ('description', models.CharField()),
                ('section', models.CharField(choices=[('H', 'Hardware Project'), ('S', 'Software Project'), ('E', 'Event'), ('P', 'Personal Project')], max_length=100)),
            ],
        ),
    ]
