# Generated by Django 5.2 on 2025-04-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0006_websection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
        migrations.DeleteModel(
            name='hardware_project',
        ),
        migrations.DeleteModel(
            name='software_project',
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.AlterField(
            model_name='websection',
            name='section',
            field=models.CharField(choices=[('hardware', 'Hardware Project'), ('software', 'Software Project'), ('event', 'Event'), ('member', 'Personal Project')], max_length=100),
        ),
    ]
