# Generated by Django 5.2 on 2025-05-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
