# Generated by Django 5.2 on 2025-05-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0003_remove_team_members_team_teammember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
