# Generated by Django 5.2 on 2025-05-05 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0004_image_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='school',
        ),
        migrations.AddField(
            model_name='team',
            name='judges',
            field=models.ManyToManyField(blank=True, null=True, related_name='judges', to=settings.AUTH_USER_MODEL),
        ),
    ]
