# Generated by Django 5.2 on 2025-05-09 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0005_remove_team_school_team_judges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='judges',
            field=models.ManyToManyField(related_name='judges', to=settings.AUTH_USER_MODEL),
        ),
    ]
