# Generated by Django 5.2 on 2025-05-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0006_alter_team_judges'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
