# Generated by Django 5.2 on 2025-05-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0007_topic_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
    ]
