# Generated by Django 5.2 on 2025-05-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0008_remove_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
