# Generated by Django 5.2 on 2025-05-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0009_alter_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
