# Generated by Django 5.2 on 2025-05-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0010_alter_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='blurb',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='blurb',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='images',
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
