# Generated by Django 5.2 on 2025-05-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0011_remove_project_blurb_remove_topic_blurb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
