# Generated by Django 5.2 on 2025-05-16 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0012_topic_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='coverImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TechApp.image'),
        ),
    ]
