# Generated by Django 5.2 on 2025-05-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0013_alter_topic_coverimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
