# Generated by Django 5.2 on 2025-05-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0015_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='ProjectUpdate',
        ),
    ]
