# Generated by Django 5.2 on 2025-05-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0017_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
