# Generated by Django 5.2 on 2025-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0018_alter_comment_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
