# Generated by Django 5.2 on 2025-05-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0023_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
