# Generated by Django 5.2 on 2025-05-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0024_alter_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='authors',
        ),
    ]
