# Generated by Django 5.2 on 2025-05-18 17:54

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0025_remove_project_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
