# Generated by Django 5.2 on 2025-05-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0026_alter_project_description_delete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blurb',
            field=models.TextField(default='This is a project blurb.', max_length=750),
        ),
    ]
