# Generated by Django 5.2 on 2025-05-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0027_project_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='blurb',
            field=models.TextField(max_length=750),
        ),
    ]
