# Generated by Django 5.2 on 2025-05-18 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0028_alter_project_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(to='TechApp.image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechApp.topic'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechApp.project'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='coverImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechApp.image'),
        ),
    ]
