# Generated by Django 5.2 on 2025-05-18 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0029_alter_image_title_alter_project_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechApp.project'),
        ),
    ]
