# Generated by Django 5.2 on 2025-05-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0031_alter_comment_content_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.IntegerField(default=0, help_text='Number of likes for this project'),
        ),
    ]
