# Generated by Django 5.2 on 2025-05-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0032_project_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tag', max_length=50, unique=True)),
                ('blurb', models.TextField(help_text='Short description of the tag', max_length=750)),
            ],
        ),
    ]
