# Generated by Django 5.2 on 2025-05-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0033_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags related to the project', to='TechApp.tag'),
        ),
    ]
