# Generated by Django 5.2 on 2025-05-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0034_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide this image from front page'),
        ),
    ]
