# Generated by Django 5.2 on 2025-05-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechApp', '0035_image_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='topic',
        ),
        migrations.AddField(
            model_name='project',
            name='topic',
            field=models.ManyToManyField(help_text='Topic(s) related to the project', to='TechApp.topic'),
        ),
    ]
