# Generated by Django 5.2 on 2025-04-28 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0002_hardware_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hardware_projects',
            new_name='hardware_project',
        ),
    ]
